// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDew5czr0EEsiJVatTQCnoa7nc0X1BXcSw',
    appId: '1:848967212274:web:ab98730038bca2707ec46b',
    messagingSenderId: '848967212274',
    projectId: 'ewm-aim',
    authDomain: 'ewm-aim.firebaseapp.com',
    storageBucket: 'ewm-aim.appspot.com',
    measurementId: 'G-J2ZEJWMC4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ7kQqTz75B9tgBAzrc7Em4nOcYAUCFu4',
    appId: '1:848967212274:android:6aa9d159a60284577ec46b',
    messagingSenderId: '848967212274',
    projectId: 'ewm-aim',
    storageBucket: 'ewm-aim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOPySHLGJCWfvu5esqr_nKN9x7zbNLSJ4',
    appId: '1:848967212274:ios:0b238a281cbf5d7b7ec46b',
    messagingSenderId: '848967212274',
    projectId: 'ewm-aim',
    storageBucket: 'ewm-aim.appspot.com',
    iosClientId: '848967212274-g6j5nfc5c1qo3o7bcquii04aco3lkp7n.apps.googleusercontent.com',
    iosBundleId: 'ewm.aim.certify',
  );
}
